name: github-ci

on:
  push:
    branches: [ main, dev ]

env:
  ECR_REPOSITORY: toyamagu-cicd-sample
  K8s_MANIFEST_REPO: toyamagu-2021/cicd-sample-k8s-manifest
  APP_NAME: sample-app
  AWS_REGION: ap-northeast-1

jobs:
  build-and-publish:
    name: Building and Pushing an Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      container-repo: ${{ steps.build-and-publish.build-image.outputs.container-repo }}
      container-tag: ${{ steps.build-and-publish.build-image.outputs.container-tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: arn:aws:iam::340084826803:role/githubactions-oidc-role
        aws-region: ${{ env.AWS_REGION }}
        

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        working-dir: "."
      run: |
        CONTAINER_REPO=${ECR_REGISTRY}/${{ env.ECR_REPOSITORY }}
        CONTAINER_TAG=${{ github.ref_name }}-${{ github.sha }}
        CONTAINER_NAME=${CONTAINER_REPO}:${CONTAINER_TAG}
        docker build -t ${CONTAINER_NAME} .
        docker push ${CONTAINER_NAME}
        echo "::set-output container-repo=${CONATIENR_REPO}"
        echo "::set-output container-tag=${CONATIENR_TAG}"

  update-k8s-manifest:
    name: Update k8s manifest
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
    - name: Set target branch
      id: set-target-branch
      run: |
        TARGET_BRANCH=$([ "${{ github.ref_name }}" == "main" ] && echo "main" || echo "dev")
        echo "Target branch is $TARGET_BRANCH"
        echo "::set-output target-branch=${TARGET_BRANCH}"

    - name: Checkout
      uses: actions/checkout@v3
      with: 
        repository: ${{ env.K8s_MANIFEST_REPO }}
        ref: ${{ steps.set-target-branch.outputs.target-branch }} 
        ssh-key: ${{ secrets.CICD_DEPLOY_KEY }}


    - name: Update K8s manifest
      env:
        CONTAINER_REPO: ${{needs.build-and-publish.outputs.container-repo}} 
        CONTAINER_TAG: ${{needs.build-and-publish.outputs.container-tag}}
      run: |
        kustomize edit set image sample-app=${CONTAINER_REPO}:${CONTAINER_TAG}
      working-directory: "${{ env.APP_NAME }}/overlays/${{ github.ref_name }}"

    - name: Git Push
      run: |
        git add .
        git commit -m "Commit hash: ${{ github.sha }}"
        git push
